dbt-cloud:
  project-id: 16897

name: databricks_university
version: "1.0.0"
config-version: 2

profile: tue_databricks

model-paths: ["models"]
macro-paths: ["macros"]
test-paths:  ["tests"]
seed-paths:  ["seeds"]

target-path: "target"
clean-targets:
  - target
  - dbt_packages

vars:
  # Dutch academic year starts in August
  academic_year_start_month: 8

models:
  databricks_university:
    staging:
      +schema: staging
      +materialized: view
      +tags: ["staging"]
    intermediate:
      +schema: intermediate
      +materialized: view
      +tags: ["intermediate"]
    marts:
      +schema: marts
      +tags: ["marts"]
      finance:
        +materialized: table
